apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: br-foundation-etl-ingress
  file_path: teste/Dockerfile
  description: Testes gerais
spec:
  type: service
  lifecycle: qa
  owner: platform
  system: system:default/base-system
